[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^2.1.0
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2