"""Build the "why not a smartwatch?" comparison data for web/compare.html.

One synthetic afternoon for the demo patient (atrial fibrillation, metoprolol, usual ~72):
seated, heart rate climbs to ~104 and stays there, with a noisy minute in the middle.
The same samples go through:
  - a typical smartwatch high-heart-rate rule: inactive and above a fixed threshold for
    10 minutes (Apple's default threshold is 120 bpm; 100 is its most sensitive setting)
  - the real CardioGlasses pipeline with the FinchNode record.

    python -m tools.compare        # writes web/compare-data.js
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from ai.contracts import Config, PatientContext
from ai.pipeline import Pipeline
from ai.replay import Scenario, _constant_hr, _linear_ramp, _piecewise, generate_scenario

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "web" / "compare-data.js"

DURATION_S = 960
ONSET_S = 120
NOISY = (400, 460)
WATCH_SUSTAIN_S = 600
WATCH_THRESHOLDS = (120, 100)

PATIENT = PatientContext(
    patient_id="patient-demo-polypharmacy",
    age=78,
    conditions=["Atrial fibrillation", "Heart failure", "Essential hypertension"],
    medications=["24 HR metoprolol succinate 50 MG Extended Release Oral Tablet", "apixaban 5 MG Oral Tablet"],
    risk_tier="high",
    config=Config(min_quality=0.6, persist_s=30, deviation_trigger=2.0, cooldown_s=120),
    clinic_resting_hr=73.5,
)


def scenario() -> Scenario:
    return Scenario(
        "af_seated_rise",
        DURATION_S,
        _piecewise((ONSET_S, _constant_hr(72)), (ONSET_S + 20, _linear_ramp(ONSET_S, ONSET_S + 20, 72, 104)),
                   (DURATION_S, _constant_hr(104))),
        seed=21,
        jitter_percent=18.0,  # irregular, like atrial fibrillation
    )


def samples():
    out = generate_scenario(scenario())
    rng = np.random.default_rng(5)
    t0 = out[0].t
    noisy = []
    for s in out:  # the glasses slip for a minute: heavy noise on the pulse signal
        if NOISY[0] <= (s.t - t0) / 1000 < NOISY[1]:
            s = s.model_copy(update={"ppg": int(s.ppg + rng.normal(0, 900))})
        noisy.append(s)
    return noisy, t0


def watch_alert(points, threshold: float):
    """First time HR has been above `threshold` while inactive for WATCH_SUSTAIN_S."""
    since = None
    for t, hr, activity in points:
        if hr is not None and hr > threshold and activity == "resting":
            since = t if since is None else since
            if t - since >= WATCH_SUSTAIN_S:
                return t
        else:
            since = None
    return None


def main() -> None:
    data, t0 = samples()
    steps = list(Pipeline(PATIENT).run(data))
    points, alerts, poor = [], [], []
    for step in steps:
        r = step.reading
        t = round((r.t - t0) / 1000)
        points.append([t, None if r.hr is None else round(r.hr, 1), r.activity])
        if r.signal_status != "ok":
            poor.append(t)
        if step.alert:
            alerts.append({"t": t, "level": step.alert.level, "headline": step.alert.headline})
    # Fair to the watch: give it the TRUE heart rate (a perfect sensor, no noise, no AF wobble),
    # so any difference comes from the rule, not the measurement. It has no notion of the record.
    truth = scenario().hr_fn
    perfect = [(t, truth(t), "resting") for t in range(0, DURATION_S + 1, 2)]
    watch = {str(th): watch_alert(perfect, th) for th in WATCH_THRESHOLDS}
    usual = next((s.reading.baseline_hr for s in reversed(steps)
                  if s.reading.baseline_hr and (s.reading.t - t0) / 1000 <= ONSET_S), None)
    payload = {
        "duration_s": DURATION_S, "onset_s": ONSET_S, "noisy": list(NOISY), "usual": usual,
        "points": [[t, hr] for t, hr, _ in points], "poor": poor, "alerts": alerts,
        "watch": watch, "watch_sustain_s": WATCH_SUSTAIN_S,
        "patient": {"age": PATIENT.age, "conditions": PATIENT.conditions[:2], "medication": "metoprolol"},
    }
    OUT.write_text("// Generated by `python -m tools.compare`; do not edit by hand.\nwindow.COMPARE = "
                   + json.dumps(payload) + ";\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: usual {usual}, CardioGlasses alerts "
          f"{[(a['t'], a['level']) for a in alerts]}, watch {watch}, weak-signal readings {len(poor)}")


if __name__ == "__main__":
    main()
